---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  repo: https://traefik.github.io/charts
  chart: traefik
  targetNamespace: traefik
  valuesContent: |-
    deployment:
      replicas: 1
    
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: "192.168.1.88"
    
    # Enable dashboard
    api:
      dashboard: true
    
    # Configure entrypoints
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
    
    # Enable Let's Encrypt
    certificatesResolvers:
      letsencrypt:
        acme:
          email: johan@ostbye.dev
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web
    
    # Persistent volume for Let's Encrypt certificates
    persistence:
      enabled: true
      size: 128Mi
    
    # Security context
    securityContext:
      capabilities:
        drop: [ALL]
      readOnlyRootFilesystem: true
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532
    
    # Ports configuration
    ports:
      web:
        port: 8000
        expose:
          default: true
        exposedPort: 80
        protocol: TCP
      websecure:
        port: 8443
        expose:
          default: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: true