apiVersion: v1
kind: Service
metadata:
  name: drone
  namespace: private
  labels:
    app: drone-server
spec:
  selector:
    app: drone-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-pvc
  namespace: private
  labels:
    app: drone-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi