---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: private
spec:
  valuesContent: |-
    gitea:
      config:
        APP_NAME: "Johan's Homelab Git - Production"
        server:
          ROOT_URL: https://git.ostbye.dev
          DOMAIN: git.ostbye.dev
          SSH_DOMAIN: git.ostbye.dev
          SSH_PORT: 2222
          SSH_LISTEN_PORT: 2222
          DISABLE_REGISTRATION: true
        security:
          INSTALL_LOCK: false
          # SECRET_KEY will be set via environment variable from secret
        database:
          DB_TYPE: postgres
          HOST: gitea-postgresql-ha-pgpool:5432
          NAME: gitea
          USER: gitea
          PASSWD: # Will be set by Helm chart
        log:
          LEVEL: Warn
        mailer:
          ENABLED: false
      admin:
        username: "admin"
        existingSecret: gitea-secrets
        secretKey: password
        email: "johan@ostbye.dev"
    # Reference the Kubernetes secret for sensitive values
    extraEnvFrom:
      - secretRef:
          name: gitea-secrets
    extraEnv:
      - name: GITEA__security__SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: gitea-secrets
            key: secret-key
    service:
      http:
        type: ClusterIP
        port: 3000
      ssh:
        type: LoadBalancer
        port: 2222
        annotations:
          metallb.universe.tf/loadBalancerIPs: "192.168.1.89"
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "local-path"
    postgresql:
      enabled: false
    mysql:
      enabled: false
    mariadb:
      enabled: false
    redis-cluster:
      enabled: false
    redis:
      enabled: false
