apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: private
spec:
  valuesContent: |-
    gitea:
      config:
        APP_NAME: "Johan's Homelab Git - Production"
        server:
          ROOT_URL: https://git.ostbye.dev
          SSH_PORT: 2222
          SSH_LISTEN_PORT: 2222
          DISABLE_REGISTRATION: true
        security:
          INSTALL_LOCK: true
          SECRET_KEY: "CHANGE_ME_IN_PRODUCTION"
        database:
          DB_TYPE: sqlite3
        log:
          LEVEL: Warn
        mailer:
          ENABLED: false
    service:
      http:
        type: ClusterIP
        port: 3000
      ssh:
        type: LoadBalancer
        port: 2222
        annotations:
          metallb.universe.tf/loadBalancerIPs: "192.168.1.100"
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "local-path"
    postgresql:
      enabled: false
    mysql:
      enabled: false
    mariadb:
      enabled: false
    redis-cluster:
      enabled: false
    redis:
      enabled: false
    gitea:
      admin:
        username: "admin"
        password: "CHANGE_ME_IN_PRODUCTION"
        email: "johan@ostbye.dev"