apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: games
  labels:
    app: minecraft
spec:
  selector:
    app: minecraft
  ports:
  - name: minecraft
    protocol: TCP
    port: 25565
    targetPort: 25565
  type: LoadBalancer