---
apiVersion: v1
kind: Namespace
metadata:
  name: private
  labels:
    app.kubernetes.io/managed-by: homelab
---
apiVersion: v1
kind: Namespace
metadata:
  name: public
  labels:
    app.kubernetes.io/managed-by: homelab
---
apiVersion: v1
kind: Namespace
metadata:
  name: offline
  labels:
    app.kubernetes.io/managed-by: homelab
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    app.kubernetes.io/managed-by: drone
---
apiVersion: v1
kind: Namespace
metadata:
  name: games
  labels:
    app.kubernetes.io/managed-by: drone
