---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secrets.yaml

secretGenerator:
  - name: cloudflare-api-token
    namespace: cert-manager
    literals:
      - token=CLOUDFLARE_TOKEN_PLACEHOLDER
    options:
      disableNameSuffixHash: true
  - name: drone-secrets
    namespace: private
    literals:
      - rpc-secret=RPC_SECRET_PLACEHOLDER
      - gitea-client-id=GITEA_CLIENT_ID_PLACEHOLDER
      - gitea-client-secret=GITEA_CLIENT_SECRET_PLACEHOLDER

patches:
  - path: patches/drone-production.yaml
  - path: patches/gitea-production.yaml
  # timestamp-patch.yaml is generated dynamically by pre-deploy.sh

images:
  - name: drone/drone
    newTag: "2.23.0"
  - name: drone/drone-runner-kube
    newTag: "1.0.0-rc.3"
