apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: private

resources:
  - ../../base/namespaces
  - ../../base/cert-manager
  - ../../base/gitea
  - ../../base/drone
  - secrets.yaml

secretGenerator:
  - name: cloudflare-api-token
    namespace: cert-manager
    literals:
      - token=CLOUDFLARE_TOKEN_PLACEHOLDER
  - name: drone-secrets
    namespace: private
    literals:
      - rpc-secret=RPC_SECRET_PLACEHOLDER
      - gitea-client-id=GITEA_CLIENT_ID_PLACEHOLDER
      - gitea-client-secret=GITEA_CLIENT_SECRET_PLACEHOLDER

patchesStrategicMerge:
  - patches/drone-production.yaml
  - patches/gitea-production.yaml
  - timestamp-patch.yaml

images:
  - name: drone/drone
    newTag: "2.23.0"
  - name: drone/drone-runner-kube
    newTag: "1.0.0-rc.3"