# Tailscale subnet routing for ostbye.dev domains
# Server acts as subnet router - all Tailscale traffic appears as home network traffic
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: tailscale-only
  namespace: private
spec:
  ipWhiteList:
    sourceRange:
      # Common home network ranges
      - "192.168.0.0/16"      # Most home networks (192.168.x.x)
      - "10.0.0.0/8"          # Private networks (10.x.x.x)
      - "172.16.0.0/12"       # Private networks (172.16-31.x.x)
      - "127.0.0.1/32"        # Localhost for health checks
      - "100.64.0.0/10"       # Tailscale IP range (100.64.x.x - 100.127.x.x)
